### ISSUE TITLE
Investigate how to enact hardforks in the Voltaire phase

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/ouroboros-consensus#60] opened 2022-11-22 16:28 UTC
The way in which the consensus layer checks the ledger state to see if a hard fork should occur will be changing with the conway ledger era. For the full background, see [CIP-1694](https://github.com/cardano-foundation/CIPs/pull/380).

The existing check has been unchanged (semantically) since the start of the shelley ledger era:

https://github.com/input-output-hk/ouroboros-network/blob/72863b0fc78abdc2b8e29f0dda96c06da3dd11d0/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Inspect.hs#L121

In other words, it currently checks that quorum-many votes agree on a protocol parameter change, which implies a hard fork in the case when the major protocol version is changed.

(I had thought that the consensus code re-used the ledger function which does the same thing, namely [votedValue](https://github.com/input-output-hk/cardano-ledger/blob/dc5331fd53e9a37daade493de1a1a01536ec64aa/eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Upec.hs#L109-L112), so perhaps the implementation details have changed.)

Starting in the conway ledger era, the new check will also inspect the ledger state, but it will instead look to see if a governance action to change the major protocol version has been staged for enactment. The exact details are still being decided.

**Comment by nfrisby** [comment] 2023-10-04 15:09
The current state of [CIP 1694](https://github.com/cardano-foundation/CIPs/tree/master/CIP-1694) (which is not yet final!) specifies that there will be exactly one full epoch between a hard fork being decided aka _ratified_ and it happening aka _enacted_.

It also currently lists the following sequence of enactments.

> Actions that have been ratified in the current epoch are prioritized as follows for enactment:
>
> - Motion of no-confidence
> - New committee/threshold
> - Update to the Constitution or proposal policy
> - Hard Fork initiation
> ...

Therefore, the `singleEraTransition` method for `ConwayEra` should become `Just e` as soon as the `e-1` to `e` epoch boundary will actually enact the hard fork initiation governance action. The only subtlety is determining whether other governance actions also scheduled for enactment on that same epoch boundary will prevent the hard fork initiation's enactment (eg as a motion of no-confidence would). But the necessary information for that should all be available simultaneously.

Thus, the ratification check at the boundary between `e` and `e+1` fully determines whether the hard fork initiation will be enacted at the boundary between epoch `e+1` and `e+2`.

And so the safe zone is for Conway is technically the duration of one epoch, and actually an exactly tight bound (ie `=` instead of a lower bound). However, Issue #389 et al currently means the transition from `Nothing` to `Just e` will actually happen as of the `k+1`st block of the epoch after the ratification boundary. Thus the safe zone is conservatively reduced to `epoch length - two stability windows`. (Our existing fundamentals only deal in increments of `k` blocks, sadly.)

**Comment by nfrisby** [comment] 2023-10-04 15:13
I changed the status to `Help needed` because this is technically blocked on the final draft of CIP-1694.

We could technically finish this task before then, but not before the relevant details (those underlying my previous comment) are confirmed as _final_.

cc @dnadales @amesgen @WhatisRT

**Comment by dnadales** [comment] 2024-01-10 14:13
@nfrisby could we close this one considering we also have [this other issue](https://github.com/IntersectMBO/ouroboros-consensus/issues/61), which is about integrating the Voltaire HF logic into Consensus, and considering you and Alex have a good understanding of how harforks work?

**Comment by dnadales** [comment] 2024-01-15 13:14
The Ledger team confirmed:

> This has been discussed a bunch of times with ledger and consensus folks and this schedule is the result of those discussions, so I don't expect any issues that would necessitate a change.

Modulo any issues found in the spec, of course.

**Comment by dnadales** [comment] 2024-01-25 10:08
Closing this issue in favour of https://github.com/IntersectMBO/ouroboros-consensus/issues/920

**Closed by dnadales** 2024-01-25 10:08 UTC
