### ISSUE TITLE
Abstraction for creating `ProtocolInfo blk` from `ProtocolParams blk`

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/ouroboros-consensus#317] opened 2023-08-23 15:29 UTC
See https://github.com/input-output-hk/ouroboros-consensus/pull/282#discussion_r1290236896

**Comment by nfrisby** [comment] 2023-08-27 23:15
FYI, I opened https://github.com/input-output-hk/ouroboros-consensus/issues/324 and assigned it to you, because I think it's related. HTH.

**Comment by amesgen** [comment] 2024-08-23 15:41
`ProtocolParams` will be removed in #1224, so I think this can also be closed by #1224.

**Comment by dnadales** [comment] 2024-10-01 12:26
This can be closed, as pointed out by @amesgen and confirmed by @jorisdral.

**Closed by dnadales** 2024-10-01 12:26 UTC
Labels: enhancement
